services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: clipboard
      POSTGRES_USER: clipboard
      POSTGRES_PASSWORD: clipboard
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clipboard"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: clipboard
      DATABASE_PASSWORD: clipboard
      DATABASE_NAME: clipboard
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  pgdata:
